# Generated by Django 4.1.2 on 2024-06-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='confirmmail',
            field=models.CharField(default='default@example.com', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='confirmpassword',
            field=models.CharField(default='ExamplePassword', max_length=20),
        ),
    ]
