# Generated by Django 4.1.2 on 2024-06-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_cliente_confirmmail_cliente_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='confirmmail',
            field=models.CharField(default='default@example.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mail',
            field=models.CharField(max_length=40),
        ),
    ]
