# Generated by Django 5.0.3 on 2024-06-23 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_cliente_confirmmail_alter_cliente_mail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreacionBoleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_boleta', models.DateField(auto_now_add=True)),
                ('desc_boleta', models.CharField(max_length=255)),
                ('cant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
            },
        ),
    ]
