# Generated by Django 5.0.3 on 2024-06-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_boletamodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreacionBoleta',
        ),
    ]
