# Generated by Django 5.0.3 on 2024-06-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_boleta_categoria_articulo_detalle_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
