# Generated by Django 5.0.3 on 2025-06-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='fecha_contrato',
            field=models.DateField(),
        ),
    ]
