# Generated by Django 5.0.3 on 2025-06-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_alter_proveedores_fecha_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
