# Generated by Django 5.0.3 on 2025-06-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_alter_proveedores_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_conocido', models.DateField()),
            ],
        ),
    ]
